version: "3.8"
services:  
  mysqldb:
    container_name: food_inflation
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:           
      - "./db/init.sql:/docker-entrypoint-initdb.d/1.sql"
  api:    
    depends_on:
      - mysqldb
    build: ./spring-social
    container_name: spring-social
    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none",
        "server.error.include-message" : "always",
        "jwt.secret" : "secret"
       }'      
    volumes:
      - ./spring-social/m2:/root/.m2
    stdin_open: true
    tty: true    
  frontend:
    build: ./react-social
    container_name: react-social
    ports:
      - '3000:3000'
    volumes:
      - ./react-social/src:/react-social/src
    links:
      - api